############################################################
############## Workflow: Image Build and Push ##############
################## INTEGRATION ENVIRONMENT #################
############################################################

########## AUTHOR:  Jan Rother
########## DATE:    2024-12
########## VERSION: 1.0

name: Integration Environment Build and Push

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build_base:
    name: Build Base Environment
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Create Artifact Directory
        id: create_artifact_dir_base
        run: mkdir -p ${{ runner.temp }}/artifacts

      - name: Setup Docker Buildx
        id: setup_buildx_base
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: false
          context: ./.envcontainer
          file: ./.envcontainer/Base.Dockerfile
          tags: ${{ vars.REPOSITORY }}/${{ vars.IMAGE }}:base-latest
          build-args: |
                      BASE_REPOSITORY=${{ vars.BASE_REPOSITORY }}
                      BASE_IMAGE=${{ vars.BASE_IMAGE }}
                      BASE_ENVIRONMENT=${{ vars.BASE_ENVIRONMENT }}
                      DENO_VERSION=${{ vars.DENO_VERSION }}
          outputs: type=docker,dest=${{ runner.temp }}/artifacts/base-environment.tar

      - name: Upload Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: base-environment
          path: ${{ runner.temp }}/artifacts/base-environment.tar

  build:
    name: Build Integration Environment
    runs-on: ubuntu-latest
    needs: build_base
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Download Image as Artifact
        uses: actions/download-artifact@v4
        with:
          name: base-environment
          path: ${{ runner.temp }}/artifacts

      - name: Load Image from Artifact
        run:  |
              docker load --input ${{ runner.temp }}/artifacts/base-environment.tar
              docker image ls -a

      - name: Create Artifact Directory
        id: create_artifact_dir_integration
        run: mkdir -p ${{ runner.temp }}/artifacts

      - name: Setup Docker Buildx
        id: setup_buildx_integration
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: false
          context: ./.envcontainer
          file: ./.envcontainer/App.Dockerfile
          tags: ${{ vars.REPOSITORY }}/${{ vars.IMAGE }}:integration-latest
          outputs: type=docker,dest=${{ runner.temp }}/artifacts/integration-environment.tar

      - name: Upload Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-environment
          path: ${{ runner.temp }}/artifacts/integration-environment.tar

  push:
    name: Push Integration Environment
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - name: Download Image as Artifact
        uses: actions/download-artifact@v4
        with:
          name: integration-environment
          path: ${{ runner.temp }}/artifacts

      - name: Load Image from Artifact
        run:  |
              docker load --input ${{ runner.temp }}/artifacts/integration-environment.tar
              docker image ls -a

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Image to Docker Hub
        run: docker push ${{ vars.REPOSITORY }}/${{ vars.IMAGE }}:integration-latest
