############################################################
############## Workflow: Image Build and Push ##############
################## INTEGRATION ENVIRONMENT #################
############################################################

########## AUTHOR:  Jan Rother
########## DATE:    2024-12
########## VERSION: 1.0

name: Integration Environment

on:
  workflow_run:
    workflows: ["Base Environment"]
    types:
      - completed

jobs:
  build:
    name: Build Integration Environment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Artifact Directory
        id: create_artifact_dir
        run: mkdir -p ${{ runner.temp }}/artifacts

      - name: Debug Build Arguments
        run: |
          echo "REPOSITORY        = docker.io/${{ vars.REPOSITORY }}"
          echo "IMAGE             = ${{ vars.IMAGE }}"

      - name: Build Image
        id: build
        uses: docker/build-push-action@v6
        with:
          pull: false
          push: false
          context: ./.envcontainer
          file: ./.envcontainer/App.Dockerfile
          tags: ${{ vars.REPOSITORY }}/${{ vars.IMAGE }}:integration-latest
          build-args: |
            BASE_REPOSITORY=docker.io/${{ vars.REPOSITORY }}
            BASE_IMAGE=${{ vars.IMAGE }}
            BASE_ENVIRONMENT=base
            BASE_RELEASE=latest
          outputs: type=docker,dest=${{ runner.temp }}/artifacts/integration-environment.tar

      - name: Upload Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-environment
          path: ${{ runner.temp }}/artifacts/integration-environment.tar

  push:
    name: Push Integration Environment
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - name: Download Image as Artifact
        uses: actions/download-artifact@v4
        with:
          name: integration-environment
          path: ${{ runner.temp }}/artifacts

      - name: Load Image from Artifact
        run: |
          docker load --input ${{ runner.temp }}/artifacts/integration-environment.tar
          docker image ls -a

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Image to Docker Hub
        run: docker push ${{ vars.REPOSITORY }}/${{ vars.IMAGE }}:integration-latest

  cancel:
    name: Cancel Integration Environment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      contents: read
    steps:
      - name: Display Cancel Message
        run: |
          echo "Workflow run 'Build and Push of Base Environment' failed."
          echo "Base Environment is required for Integration Environment."
          echo "========================================================="
          echo "INFO: Integration Environment canceled."

      - name: Cancel Workflow
        run: exit 0
